<a href="https://colab.research.google.com/github/sujay-borse/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Basic Array Creation**

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
a = [1,2,3.5]

In [ ]:
a

[1, 2, 3.5]

In [ ]:
np.array(a)

array([1. , 2. , 3.5])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
arr = np.arange(1,11,2)

In [ ]:
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((4,8))

In [ ]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((3,5))

In [ ]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0,1,100)

In [ ]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**Random Generation function**

In [ ]:
np.random.rand(10)

array([0.16475808, 0.04451556, 0.84373792, 0.68946431, 0.9778311 ,
       0.03968373, 0.69972465, 0.17859761, 0.54430609, 0.29146772])

In [ ]:
np.random.randn(10)

array([-1.29552212,  0.50791822, -1.32467916, -0.41270212, -1.07404972,
       -1.66085764,  0.64157557,  1.52159151,  0.98357267, -0.14391508])

In [ ]:
np.random.randint(10,20,10)

array([17, 19, 13, 12, 14, 10, 10, 17, 19, 18])

**Array Attributes**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

**Array Methods**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr.argmax()

np.int64(8)

**Reshaping and resizing**

In [ ]:
arr = np.arange(1,31)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [ ]:
arr[4]

np.int64(15)

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr = np.arange(1,31).reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]


array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

**ARRAY OPERATIONS**

Arithmetic operations


In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1 // a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
a1 *2

array([ 2,  4,  6,  8, 10])

Broadcasting

In [ ]:
l =[10,20,30,40]

In [ ]:
arr = np.array(l)

In [ ]:
arr + 10

array([20, 30, 40, 50])

In [ ]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

Deep and Shallow copy

In [ ]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice= slice*10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[4:6]*10

array([50, 60])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b = a.copy()

In [ ]:
b[0] = 99


In [ ]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [ ]:
a = np.array([[1,2],[3,4]])
b =  np.array([[5,6],[7,8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

Stacking Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [ ]:
c = np.arange(16).reshape(4,4)

In [ ]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

**Exercise**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students.
np.mean(data[:,1])

np.float64(81.6)

In [ ]:
#Extract Math marks of all students.
a = np.array(data[:,1])
a

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]


array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
data[data[:,0] < 19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
data.mean(axis = 0)

array([18.4, 81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] > 80) & (data[:,2] > 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75 , 2 ] = 0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])